---
title: "Untitled"
author: "Vanshika Tibarewalla"
date: "19/05/2022"
output: html_document
---

```{r setup, include=FALSE}
#installing libraries:
library(readxl)
library(lubridate) 
library(tseries)
library(dplyr)
library(DataCombine)
library(xts)
library(zoo)
library(forecast)
library(stringr)
library(tidyr)
library(dplyr)
library(ggplot2)

#reading data
df = read.csv("/Users/vanshikatib/Downloads/stock_price_and_sentiment.csv")

#checking format:
str(df)

```

```{r cars}
summary(df)
```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(df)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.

```{r}
#converting to date column
df[,1] <- as.Date(df[,1])


```

```{r}
#head(df)
#tail(df)

#df$Close= as.numeric(df$Close)

keeps <- c("Date", "Close")
df = df[keeps]

summary(df)
str(df)
```

```{r}
#converting to xts
df <- xts(df, order.by = df$Date)

#removing first column
df <- df[,-1]
```

```{r}
df_num = as.numeric(df)
ts.plot(df_num)
acf(df_num)
```
```{r}
#tsfeatures package

#install.packages("tsfeatures")
library("tsfeatures")
```

```{r}
res= tsfeatures(df_num)

```
```{r}
entropy(df_num)
```

```{r}
hurst(df_num)
```

```{r}
stl_features(df_num)
```

```{r}

```

